const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Particles,
		C3.Behaviors.scrollto,
		C3.Plugins.Mouse,
		C3.Behaviors.Fade,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerBackground,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Text.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Exps.left
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{Item: 0},
	{Touch: 0},
	{Keyboard: 0},
	{ID: 0},
	{Pin: 0},
	{Text_item: 0},
	{AJAX: 0},
	{Array_Words: 0},
	{Array_line_uid: 0},
	{First_x: 0},
	{First_y: 0},
	{Spawner: 0},
	{Particles: 0},
	{ScrollTo: 0},
	{Background: 0},
	{Particles2: 0},
	{Particles3: 0},
	{Text_log: 0},
	{Match_show: 0},
	{Text_match: 0},
	{restart_btn: 0},
	{Mouse: 0},
	{Text_loading: 0},
	{Fade: 0},
	{Transition_img: 0},
	{LocalStorage: 0},
	{Key: 0},
	{Text_key: 0},
	{Backspace: 0},
	{Text_msg: 0},
	{Text_current: 0},
	{Array_line_letter: 0},
	{Text_word: 0},
	{Continue: 0},
	{Browser: 0},
	{Control: 0},
	{Speed: 0},
	{Score: 0},
	{found: 0},
	{Hiscore: 0},
	{Transition: 0},
	{Next: 0},
	{lastLetter: 0},
	{Word: 0},
	{x: 0},
	{y: 0},
	{var: 0},
	{is_letter: 0},
	{Variable1: 0},
	{Variable2: 0},
	{Variable3: 0},
	{In_Out: 0},
	{text_input: 0}
];

self.InstanceType = {
	Item: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Text_item: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	Array_Words: class extends self.IArrayInstance {},
	Array_line_uid: class extends self.IArrayInstance {},
	Spawner: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Background: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Text_log: class extends self.ITextInstance {},
	Match_show: class extends self.ISpriteInstance {},
	Text_match: class extends self.ITextInstance {},
	restart_btn: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Text_loading: class extends self.ITextInstance {},
	Transition_img: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Key: class extends self.ISpriteInstance {},
	Text_key: class extends self.ITextInstance {},
	Backspace: class extends self.ISpriteInstance {},
	Text_msg: class extends self.ITextInstance {},
	Text_current: class extends self.ITextInstance {},
	Array_line_letter: class extends self.IArrayInstance {},
	Text_word: class extends self.ITextInstance {},
	Continue: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {}
}